export const customerService = {
  getCustomerList() {
    return Promise.resolve([
      {
        id: 1,
        name: "Alice",
        totalSpent: 59.99,
        firstRentedDate: "2025-03-30",
        rentedTimes: 1,
      },
      {
        id: 2,
        name: "Bob",
        totalSpent: 49.99,
        firstRentedDate: "2025-03-31",
        rentedTimes: 1,
      },
      {
        id: 3,
        name: "Charlie",
        totalSpent: 49.99,
        firstRentedDate: "2025-04-01",
        rentedTimes: 1,
      },
      {
        id: 4,
        name: "David",
        totalSpent: 54.99,
        firstRentedDate: "2025-04-02",
        rentedTimes: 1,
      },
      {
        id: 5,
        name: "Emma",
        totalSpent: 59.99,
        firstRentedDate: "2025-03-29",
        rentedTimes: 1,
      },
      {
        id: 6,
        name: "Frank",
        totalSpent: 49.99,
        firstRentedDate: "2025-04-03",
        rentedTimes: 1,
      },
      {
        id: 7,
        name: "Grace",
        totalSpent: 59.99,
        firstRentedDate: "2025-04-04",
        rentedTimes: 1,
      },
      {
        id: 8,
        name: "Hannah",
        totalSpent: 49.99,
        firstRentedDate: "2025-03-28",
        rentedTimes: 1,
      },
      {
        id: 9,
        name: "Isaac",
        totalSpent: 59.99,
        firstRentedDate: "2025-04-05",
        rentedTimes: 1,
      },
      {
        id: 10,
        name: "Jack",
        totalSpent: 59.99,
        firstRentedDate: "2025-04-06",
        rentedTimes: 1,
      },
      {
        id: 11,
        name: "Katie",
        totalSpent: 49.99,
        firstRentedDate: "2025-04-07",
        rentedTimes: 1,
      },
      {
        id: 12,
        name: "Leo",
        totalSpent: 59.99,
        firstRentedDate: "2025-04-08",
        rentedTimes: 1,
      },
      {
        id: 13,
        name: "Mia",
        totalSpent: 59.99,
        firstRentedDate: "2025-04-09",
        rentedTimes: 1,
      },
      {
        id: 14,
        name: "Nathan",
        totalSpent: 59.99,
        firstRentedDate: "2025-04-10",
        rentedTimes: 1,
      },
      {
        id: 15,
        name: "Olivia",
        totalSpent: 59.99,
        firstRentedDate: "2025-03-27",
        rentedTimes: 1,
      },
      {
        id: 16,
        name: "Peter",
        totalSpent: 59.99,
        firstRentedDate: "2025-04-11",
        rentedTimes: 1,
      },
      {
        id: 17,
        name: "Quinn",
        totalSpent: 49.99,
        firstRentedDate: "2025-04-12",
        rentedTimes: 1,
      },
      {
        id: 18,
        name: "Rachel",
        totalSpent: 59.99,
        firstRentedDate: "2025-04-13",
        rentedTimes: 1,
      },
      {
        id: 19,
        name: "Sam",
        totalSpent: 59.99,
        firstRentedDate: "2025-04-14",
        rentedTimes: 1,
      },
      {
        id: 20,
        name: "Tina",
        totalSpent: 49.99,
        firstRentedDate: "2025-04-15",
        rentedTimes: 1,
      },
    ]);
  },
};
