export const productService = {
  getProducts() {
    return Promise.resolve([
      {
        id: 1,
        name: "The Legend of Zelda: Breath of the Wild",
        category: "Action-Adventure",
        price: 59.99,
        status: "available",
      },
      {
        id: 2,
        name: "Super Mario Odyssey",
        category: "Platformer",
        price: 49.99,
        status: "available",
      },
      {
        id: 3,
        name: "Animal Crossing: New Horizons",
        category: "Life Simulation",
        price: 54.99,
        status: "available",
      },
      {
        id: 4,
        name: "Metroid Dread",
        category: "Action",
        price: 39.99,
        status: "available",
      },
      {
        id: 5,
        name: "Super Smash Bros. Ultimate",
        category: "Fighting",
        price: 59.99,
        status: "out of stock",
      },
      {
        id: 6,
        name: "Splatoon 3",
        category: "Shooter",
        price: 59.99,
        status: "available",
      },
      {
        id: 7,
        name: "Mario Kart 8 Deluxe",
        category: "Racing",
        price: 49.99,
        status: "available",
      },
      {
        id: 8,
        name: "Pokémon Scarlet",
        category: "RPG",
        price: 59.99,
        status: "available",
      },
      {
        id: 9,
        name: "Pokémon Violet",
        category: "RPG",
        price: 59.99,
        status: "out of stock",
      },
      {
        id: 10,
        name: "Luigi’s Mansion 3",
        category: "Adventure",
        price: 49.99,
        status: "available",
      },
      {
        id: 11,
        name: "Fire Emblem Engage",
        category: "Strategy RPG",
        price: 59.99,
        status: "available",
      },
      {
        id: 12,
        name: "Xenoblade Chronicles 3",
        category: "JRPG",
        price: 59.99,
        status: "available",
      },
      {
        id: 13,
        name: "Kirby and the Forgotten Land",
        category: "Platformer",
        price: 54.99,
        status: "available",
      },
      {
        id: 14,
        name: "Bayonetta 3",
        category: "Hack and Slash",
        price: 49.99,
        status: "out of stock",
      },
      {
        id: 15,
        name: "Mario Party Superstars",
        category: "Party",
        price: 49.99,
        status: "available",
      },
      {
        id: 16,
        name: "Donkey Kong Country: Tropical Freeze",
        category: "Platformer",
        price: 39.99,
        status: "available",
      },
      {
        id: 17,
        name: "Yoshi’s Crafted World",
        category: "Platformer",
        price: 49.99,
        status: "available",
      },
      {
        id: 18,
        name: "Octopath Traveler II",
        category: "JRPG",
        price: 59.99,
        status: "available",
      },
      {
        id: 19,
        name: "Triangle Strategy",
        category: "Tactical RPG",
        price: 59.99,
        status: "available",
      },
      {
        id: 20,
        name: "Advance Wars 1+2: Re-Boot Camp",
        category: "Turn-Based Strategy",
        price: 49.99,
        status: "available",
      },
      {
        id: 21,
        name: "Hollow Knight: Silksong",
        category: "Metroidvania",
        price: 34.99,
        status: "coming soon",
      },
      {
        id: 22,
        name: "Persona 5 Royal",
        category: "JRPG",
        price: 59.99,
        status: "available",
      },
      {
        id: 23,
        name: "Shin Megami Tensei V",
        category: "JRPG",
        price: 59.99,
        status: "available",
      },
      {
        id: 24,
        name: "No More Heroes III",
        category: "Hack and Slash",
        price: 49.99,
        status: "available",
      },
      {
        id: 25,
        name: "Astral Chain",
        category: "Action",
        price: 49.99,
        status: "available",
      },
      {
        id: 26,
        name: "Monster Hunter Rise",
        category: "Action RPG",
        price: 39.99,
        status: "available",
      },
      {
        id: 27,
        name: "Dragon Quest XI S: Echoes of an Elusive Age",
        category: "JRPG",
        price: 49.99,
        status: "available",
      },
      {
        id: 28,
        name: "Tears of the Kingdom",
        category: "Action-Adventure",
        price: 69.99,
        status: "available",
      },
      {
        id: 29,
        name: "Pikmin 4",
        category: "Puzzle Strategy",
        price: 49.99,
        status: "available",
      },
      {
        id: 30,
        name: "The Legend of Zelda: Link’s Awakening",
        category: "Action-Adventure",
        price: 49.99,
        status: "available",
      },
    ]);
  },
};
