export const rentedService = {
  getRentedGames() {
    return Promise.resolve([
      {
        id: 1,
        name: "The Legend of Zelda: Breath of the Wild",
        category: "Action-Adventure",
        price: 59.99,
        rentedBy: "Alice",
        rentedDate: "2025-03-30",
        returnDate: "2025-04-10",
      },
      {
        id: 2,
        name: "Super Mario Odyssey",
        category: "Platformer",
        price: 49.99,
        rentedBy: "Bob",
        rentedDate: "2025-03-31",
        returnDate: "2025-04-12",
      },
      {
        id: 3,
        name: "Mario Kart 8 Deluxe",
        category: "Racing",
        price: 49.99,
        rentedBy: "Charlie",
        rentedDate: "2025-04-01",
        returnDate: "2025-04-15",
      },
      {
        id: 4,
        name: "Animal Crossing: New Horizons",
        category: "Life Simulation",
        price: 54.99,
        rentedBy: "David",
        rentedDate: "2025-04-02",
        returnDate: "2025-04-18",
      },
      {
        id: 5,
        name: "Pokémon Scarlet",
        category: "RPG",
        price: 59.99,
        rentedBy: "Emma",
        rentedDate: "2025-03-29",
        returnDate: "2025-04-08",
      },
      {
        id: 6,
        name: "Luigi’s Mansion 3",
        category: "Adventure",
        price: 49.99,
        rentedBy: "Frank",
        rentedDate: "2025-04-03",
        returnDate: "2025-04-14",
      },
      {
        id: 7,
        name: "Xenoblade Chronicles 3",
        category: "JRPG",
        price: 59.99,
        rentedBy: "Grace",
        rentedDate: "2025-04-04",
        returnDate: "2025-04-20",
      },
      {
        id: 8,
        name: "Kirby and the Forgotten Land",
        category: "Platformer",
        price: 49.99,
        rentedBy: "Hannah",
        rentedDate: "2025-03-28",
        returnDate: "2025-04-17",
      },
      {
        id: 9,
        name: "Bayonetta 3",
        category: "Hack and Slash",
        price: 59.99,
        rentedBy: "Isaac",
        rentedDate: "2025-04-05",
        returnDate: "2025-04-11",
      },
      {
        id: 11,
        name: "Fire Emblem Engage",
        category: "Strategy RPG",
        price: 59.99,
        rentedBy: "Jack",
        rentedDate: "2025-04-06",
        returnDate: "2025-04-13",
      },
      {
        id: 11,
        name: "Donkey Kong Country: Tropical Freeze",
        category: "Platformer",
        price: 49.99,
        rentedBy: "Katie",
        rentedDate: "2025-04-07",
        returnDate: "2025-04-19",
      },
      {
        id: 12,
        name: "Splatoon 3",
        category: "Shooter",
        price: 59.99,
        rentedBy: "Leo",
        rentedDate: "2025-04-08",
        returnDate: "2025-04-21",
      },
      {
        id: 13,
        name: "Persona 5 Royal",
        category: "JRPG",
        price: 59.99,
        rentedBy: "Mia",
        rentedDate: "2025-04-09",
        returnDate: "2025-04-22",
      },
      {
        id: 14,
        name: "Octopath Traveler II",
        category: "JRPG",
        price: 59.99,
        rentedBy: "Nathan",
        rentedDate: "2025-04-10",
        returnDate: "2025-04-25",
      },
      {
        id: 15,
        name: "Triangle Strategy",
        category: "Tactical RPG",
        price: 59.99,
        rentedBy: "Olivia",
        rentedDate: "2025-03-27",
        returnDate: "2025-04-09",
      },
      {
        id: 16,
        name: "Advance Wars 1+2: Re-Boot Camp",
        category: "Turn-Based Strategy",
        price: 59.99,
        rentedBy: "Peter",
        rentedDate: "2025-04-11",
        returnDate: "2025-04-16",
      },
      {
        id: 17,
        name: "Hollow Knight: Silksong",
        category: "Metroidvania",
        price: 49.99,
        rentedBy: "Quinn",
        rentedDate: "2025-04-12",
        returnDate: "2025-04-23",
      },
      {
        id: 18,
        name: "Pikmin 4",
        category: "Puzzle Strategy",
        price: 59.99,
        rentedBy: "Rachel",
        rentedDate: "2025-04-13",
        returnDate: "2025-04-24",
      },
      {
        id: 19,
        name: "Monster Hunter Rise",
        category: "Action RPG",
        price: 59.99,
        rentedBy: "Sam",
        rentedDate: "2025-04-14",
        returnDate: "2025-04-26",
      },
      {
        id: 20,
        name: "The Legend of Zelda: Link’s Awakening",
        category: "Action-Adventure",
        price: 49.99,
        rentedBy: "Tina",
        rentedDate: "2025-04-15",
        returnDate: "2025-04-28",
      },
    ]);
  },
};
